import React from 'react';
import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';
import d from '../../../assets/img/map-point-svgrepo-com.svg'
import {ILocation} from "../../../interfaces/common";

const customIcon = L.icon({
    iconUrl: '/map-point-svgrepo-com.svg',
    iconSize: [40, 40],
    iconAnchor: [20, 40],
});

const places = [
        {
            "id": 4020,
            "name": "Auchan",
            "lat": 49.812416,
            "long": 23.9864521,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": true,
            "induction_loops": false,
            "visual_audio_signals": false,
            "lowered_counters": false,
            "assistance_service": false,
            "guide_paths": false,
            "elevator": true,
            "seating_with_armrests": true,
            "hearing_access": "no_access",
            "wheelchair_access_level": "full",
            "vision_access_level": "partial",
            "cognitive_access_level": "no_access"
        },
        {
            "id": 4113,
            "name": "Свій маркет",
            "lat": 49.8171252,
            "long": 24.0765414,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": true,
            "induction_loops": true,
            "visual_audio_signals": false,
            "lowered_counters": true,
            "assistance_service": false,
            "guide_paths": false,
            "elevator": false,
            "seating_with_armrests": false,
            "hearing_access": "partial",
            "wheelchair_access_level": "partial",
            "vision_access_level": "partial",
            "cognitive_access_level": "no_access"
        },
        {
            "id": 4024,
            "name": "Сільпо",
            "lat": 49.8493368,
            "long": 24.0212312,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": false,
            "induction_loops": false,
            "visual_audio_signals": false,
            "lowered_counters": false,
            "assistance_service": false,
            "guide_paths": true,
            "elevator": false,
            "seating_with_armrests": false,
            "hearing_access": "no_access",
            "wheelchair_access_level": "partial",
            "vision_access_level": "partial",
            "cognitive_access_level": "no_access"
        },
        {
            "id": 4077,
            "name": "АТБ-маркет",
            "lat": 49.7952832,
            "long": 24.0593929,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": true,
            "disabled_parking": false,
            "braille_signs": false,
            "induction_loops": false,
            "visual_audio_signals": false,
            "lowered_counters": true,
            "assistance_service": false,
            "guide_paths": true,
            "elevator": true,
            "seating_with_armrests": false,
            "hearing_access": "no_access",
            "wheelchair_access_level": "full",
            "vision_access_level": "partial",
            "cognitive_access_level": "no_access"
        },
        {
            "id": 4079,
            "name": "Свій маркет",
            "lat": 49.7973244,
            "long": 24.0206416,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": true,
            "induction_loops": false,
            "visual_audio_signals": true,
            "lowered_counters": true,
            "assistance_service": false,
            "guide_paths": false,
            "elevator": true,
            "seating_with_armrests": true,
            "hearing_access": "partial",
            "wheelchair_access_level": "full",
            "vision_access_level": "partial",
            "cognitive_access_level": "no_access"
        },
        {
            "id": 4052,
            "name": "Близенько",
            "lat": 49.8260964,
            "long": 24.0381022,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": true,
            "induction_loops": false,
            "visual_audio_signals": false,
            "lowered_counters": false,
            "assistance_service": false,
            "guide_paths": true,
            "elevator": true,
            "seating_with_armrests": true,
            "hearing_access": "no_access",
            "wheelchair_access_level": "full",
            "vision_access_level": "full",
            "cognitive_access_level": "no_access"
        },
        {
            "id": 4211,
            "name": "АТБ-маркет",
            "lat": 49.81237951501442,
            "long": 23.998185938953004,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": true,
            "disabled_parking": false,
            "braille_signs": false,
            "induction_loops": false,
            "visual_audio_signals": true,
            "lowered_counters": false,
            "assistance_service": true,
            "guide_paths": false,
            "elevator": true,
            "seating_with_armrests": true,
            "hearing_access": "partial",
            "wheelchair_access_level": "full",
            "vision_access_level": "no_access",
            "cognitive_access_level": "full"
        },
        {
            "id": 4059,
            "name": "Хлібна корзина",
            "lat": 49.8232003,
            "long": 23.966,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": true,
            "induction_loops": true,
            "visual_audio_signals": false,
            "lowered_counters": true,
            "assistance_service": true,
            "guide_paths": true,
            "elevator": false,
            "seating_with_armrests": true,
            "hearing_access": "partial",
            "wheelchair_access_level": "partial",
            "vision_access_level": "full",
            "cognitive_access_level": "full"
        },
        {
            "id": 4095,
            "name": "Продукти Напої Тютюн",
            "lat": 49.7980118,
            "long": 24.0484924,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": true,
            "induction_loops": false,
            "visual_audio_signals": false,
            "lowered_counters": true,
            "assistance_service": false,
            "guide_paths": true,
            "elevator": false,
            "seating_with_armrests": false,
            "hearing_access": "no_access",
            "wheelchair_access_level": "partial",
            "vision_access_level": "full",
            "cognitive_access_level": "no_access"
        },
        {
            "id": 4208,
            "name": "АТБ-маркет",
            "lat": 49.789633511711386,
            "long": 24.01760821424396,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": true,
            "disabled_parking": false,
            "braille_signs": true,
            "induction_loops": false,
            "visual_audio_signals": false,
            "lowered_counters": true,
            "assistance_service": true,
            "guide_paths": true,
            "elevator": true,
            "seating_with_armrests": false,
            "hearing_access": "no_access",
            "wheelchair_access_level": "full",
            "vision_access_level": "full",
            "cognitive_access_level": "full"
        },
        {
            "id": 4037,
            "name": "Сім23",
            "lat": 49.7846466,
            "long": 24.0601934,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": true,
            "disabled_parking": false,
            "braille_signs": false,
            "induction_loops": true,
            "visual_audio_signals": false,
            "lowered_counters": true,
            "assistance_service": false,
            "guide_paths": true,
            "elevator": false,
            "seating_with_armrests": false,
            "hearing_access": "partial",
            "wheelchair_access_level": "partial",
            "vision_access_level": "partial",
            "cognitive_access_level": "no_access"
        },
        {
            "id": 4108,
            "name": "Овочі та фрукти",
            "lat": 49.8230222,
            "long": 23.9601968,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": true,
            "induction_loops": true,
            "visual_audio_signals": true,
            "lowered_counters": true,
            "assistance_service": false,
            "guide_paths": true,
            "elevator": true,
            "seating_with_armrests": false,
            "hearing_access": "full",
            "wheelchair_access_level": "full",
            "vision_access_level": "full",
            "cognitive_access_level": "no_access"
        },
        {
            "id": 4066,
            "name": "Продукти",
            "lat": 49.7968766,
            "long": 24.05952,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": true,
            "induction_loops": true,
            "visual_audio_signals": true,
            "lowered_counters": true,
            "assistance_service": true,
            "guide_paths": false,
            "elevator": true,
            "seating_with_armrests": false,
            "hearing_access": "full",
            "wheelchair_access_level": "full",
            "vision_access_level": "partial",
            "cognitive_access_level": "full"
        },
        {
            "id": 4082,
            "name": "Фермерське м'яско",
            "lat": 49.7980846,
            "long": 24.0476286,
            "category": "foodmarket",
            "wheelchair_access": false,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": false,
            "induction_loops": true,
            "visual_audio_signals": true,
            "lowered_counters": false,
            "assistance_service": true,
            "guide_paths": true,
            "elevator": true,
            "seating_with_armrests": false,
            "hearing_access": "full",
            "wheelchair_access_level": "partial",
            "vision_access_level": "partial",
            "cognitive_access_level": "full"
        },
        {
            "id": 4043,
            "name": "Наш",
            "lat": 49.7958909,
            "long": 24.0628918,
            "category": "foodmarket",
            "wheelchair_access": false,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": false,
            "induction_loops": true,
            "visual_audio_signals": false,
            "lowered_counters": true,
            "assistance_service": false,
            "guide_paths": false,
            "elevator": true,
            "seating_with_armrests": true,
            "hearing_access": "partial",
            "wheelchair_access_level": "partial",
            "vision_access_level": "no_access",
            "cognitive_access_level": "no_access"
        },
        {
            "id": 4051,
            "name": "Близенько",
            "lat": 49.8261511,
            "long": 24.0269695,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": false,
            "disabled_parking": false,
            "braille_signs": false,
            "induction_loops": false,
            "visual_audio_signals": true,
            "lowered_counters": true,
            "assistance_service": true,
            "guide_paths": false,
            "elevator": false,
            "seating_with_armrests": false,
            "hearing_access": "partial",
            "wheelchair_access_level": "partial",
            "vision_access_level": "no_access",
            "cognitive_access_level": "full"
        },
        {
            "id": 4056,
            "name": "АТБ-маркет",
            "lat": 49.7824413,
            "long": 24.0570955,
            "category": "foodmarket",
            "wheelchair_access": false,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": false,
            "induction_loops": false,
            "visual_audio_signals": true,
            "lowered_counters": true,
            "assistance_service": false,
            "guide_paths": true,
            "elevator": false,
            "seating_with_armrests": false,
            "hearing_access": "partial",
            "wheelchair_access_level": "partial",
            "vision_access_level": "partial",
            "cognitive_access_level": "no_access"
        },
        {
            "id": 4065,
            "name": "Свій маркет",
            "lat": 49.8291007,
            "long": 23.9683801,
            "category": "foodmarket",
            "wheelchair_access": false,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": true,
            "induction_loops": true,
            "visual_audio_signals": true,
            "lowered_counters": true,
            "assistance_service": false,
            "guide_paths": false,
            "elevator": true,
            "seating_with_armrests": false,
            "hearing_access": "full",
            "wheelchair_access_level": "partial",
            "vision_access_level": "partial",
            "cognitive_access_level": "no_access"
        },
        {
            "id": 4072,
            "name": "Auchan",
            "lat": 49.8555394,
            "long": 24.0237549,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": false,
            "disabled_parking": true,
            "braille_signs": false,
            "induction_loops": true,
            "visual_audio_signals": false,
            "lowered_counters": false,
            "assistance_service": true,
            "guide_paths": false,
            "elevator": true,
            "seating_with_armrests": true,
            "hearing_access": "partial",
            "wheelchair_access_level": "partial",
            "vision_access_level": "no_access",
            "cognitive_access_level": "full"
        },
        {
            "id": 4076,
            "name": "АТБ-Маркет",
            "lat": 49.8236075,
            "long": 23.9678147,
            "category": "foodmarket",
            "wheelchair_access": true,
            "accessible_toilet": false,
            "disabled_parking": true,
            "braille_signs": true,
            "induction_loops": true,
            "visual_audio_signals": false,
            "lowered_counters": false,
            "assistance_service": true,
            "guide_paths": true,
            "elevator": false,
            "seating_with_armrests": false,
            "hearing_access": "partial",
            "wheelchair_access_level": "partial",
            "vision_access_level": "full",
            "cognitive_access_level": "full"
        },
        {
            "id": 3996,
            "name": "WineTime",
            "lat": 49.8554072,
            "long": 24.0217699,
            "category": "foodmarket",
            "wheelchair_access": false,
            "accessible_toilet": true,
            "disabled_parking": false,
            "braille_signs": false,
            "induction_loops": true,
            "visual_audio_signals": true,
            "lowered_counters": true,
            "assistance_service": false,
            "guide_paths": true,
            "elevator": false,
            "seating_with_armrests": true,
            "hearing_access": "full",
            "wheelchair_access_level": "partial",
            "vision_access_level": "partial",
            "cognitive_access_level": "no_access"
        },
        {
            "id": 4089,
            "name": "Родинна ковбаска",
            "lat": 49.8226034,
            "long": 23.9647624,
            "category": "foodmarket",
            "wheelchair_access": false,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": false,
            "induction_loops": true,
            "visual_audio_signals": true,
            "lowered_counters": false,
            "assistance_service": true,
            "guide_paths": false,
            "elevator": true,
            "seating_with_armrests": true,
            "hearing_access": "full",
            "wheelchair_access_level": "partial",
            "vision_access_level": "no_access",
            "cognitive_access_level": "full"
        },
        {
            "id": 4094,
            "name": "Близенько",
            "lat": 49.8114715,
            "long": 24.0358409,
            "category": "foodmarket",
            "wheelchair_access": false,
            "accessible_toilet": true,
            "disabled_parking": false,
            "braille_signs": true,
            "induction_loops": true,
            "visual_audio_signals": true,
            "lowered_counters": true,
            "assistance_service": true,
            "guide_paths": false,
            "elevator": false,
            "seating_with_armrests": false,
            "hearing_access": "full",
            "wheelchair_access_level": "partial",
            "vision_access_level": "partial",
            "cognitive_access_level": "full"
        },
        {
            "id": 4100,
            "name": "Рукавичка",
            "lat": 49.8541865,
            "long": 24.0279853,
            "category": "foodmarket",
            "wheelchair_access": false,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": true,
            "induction_loops": false,
            "visual_audio_signals": false,
            "lowered_counters": false,
            "assistance_service": true,
            "guide_paths": false,
            "elevator": false,
            "seating_with_armrests": false,
            "hearing_access": "no_access",
            "wheelchair_access_level": "partial",
            "vision_access_level": "partial",
            "cognitive_access_level": "full"
        },
        {
            "id": 4101,
            "name": "Рукавичка",
            "lat": 49.8314918,
            "long": 24.0026151,
            "category": "foodmarket",
            "wheelchair_access": false,
            "accessible_toilet": true,
            "disabled_parking": true,
            "braille_signs": false,
            "induction_loops": true,
            "visual_audio_signals": true,
            "lowered_counters": false,
            "assistance_service": false,
            "guide_paths": false,
            "elevator": true,
            "seating_with_armrests": true,
            "hearing_access": "full",
            "wheelchair_access_level": "partial",
            "vision_access_level": "no_access",
            "cognitive_access_level": "no_access"
        },
];

interface MapProps {
    onMarkerClick: (place: any) => void;
    locations: ILocation[];
}

const Map: React.FC<MapProps> = ({ onMarkerClick, locations }) => {
    return (
        <MapContainer center={[49.8397, 24.0297]} zoom={13} scrollWheelZoom={false} style={{ height: '100vh', width: 'min(100svw, 576px)' }}>
            <TileLayer
                attribution='&copy; OpenStreetMap contributors'
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            />
            {locations?.map((place) => (
                <Marker
                    key={place.id}
                    position={[place.lat, place.long]}
                    icon={customIcon}

                    eventHandlers={{
                        click: () => onMarkerClick(place),
                    }}
                />
            ))}
        </MapContainer>
    );
};

export default Map;
